In [1]:
import numpy as np


In [4]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [6]:
a=np.arange(5,20)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
a=np.arange(5,100,6)
a

array([ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83, 89, 95])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5.int
)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (368636806.py, line 1)

In [11]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [12]:
np.ones(5,chr)

TypeError: Cannot interpret '<built-in function chr>' as a data type

In [13]:
np.ones(5,short)

NameError: name 'short' is not defined

In [14]:
np.ones(5,20,2,int)

TypeError: ones() takes from 1 to 3 positional arguments but 4 were given

In [15]:
np.linspace(0,22,5)

array([ 0. ,  5.5, 11. , 16.5, 22. ])

In [16]:
np.i(10)

AttributeError: module 'numpy' has no attribute 'i'

In [17]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
np.random.randint(10,40,30)

array([39, 34, 31, 18, 34, 15, 16, 13, 29, 32, 26, 24, 38, 10, 15, 34, 28,
       18, 23, 10, 33, 32, 22, 38, 15, 34, 23, 39, 20, 39])

In [21]:
a=np.eye(5)

In [22]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
a=a.T

In [24]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a[0][4]=5

In [26]:
a


array([[1., 0., 0., 0., 5.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a=a.T

In [28]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [5., 0., 0., 0., 1.]])

In [29]:
a=np.arange(20)

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
print(a[4])

4


In [32]:
print(a[3,11])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [33]:

print(a[3:12])

[ 3  4  5  6  7  8  9 10 11]


In [34]:
print(a[])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2129586007.py, line 1)

In [35]:
print(a[:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [36]:
a[5:10]=0
a

array([ 0,  1,  2,  3,  4,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
a=np.array(np.arange(3),np.arangr(3),np.arange(3))
a

AttributeError: module 'numpy' has no attribute 'arangr'

In [38]:
a=np.arange(np.arange(3),np.arange(3),np.arange(3))
a


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
a=np.arange([1,2,3],[5,6,7],[6,5,4])
a


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [40]:
a=np.arange([[1,2,3],[5,6,7],[6,5,4]])
a


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [41]:
a=np.array([[1,2,3],[5,6,7],[6,5,4]])
a


array([[1, 2, 3],
       [5, 6, 7],
       [6, 5, 4]])

In [42]:
a[:]

array([[1, 2, 3],
       [5, 6, 7],
       [6, 5, 4]])

In [43]:
a[1:]

array([[5, 6, 7],
       [6, 5, 4]])

In [44]:
a[1,2]

7

In [45]:
a[:,:]

array([[1, 2, 3],
       [5, 6, 7],
       [6, 5, 4]])